### ISSUE TITLE
Return application/soap+xml content-type for failure messages?

### ISSUE THREAD

**Issue by surangak** [jembi/openhim-mediator-xds#17]
When an orchestration fails due to an unregistered patient or facility, the HIM returns a response of 
content-type:	text/plain; charset=utf-8
Unfortunately, it seems that dcm4chee supports only application/soap+xml. Given that we heavily depend on dcm4che, can we switch to returning a application/soap+xml response instead? :-)

**Comment by devcritter** [comment]
Certainly; it's probably more correct ito behaviour in fact. Just to note we'll have to wrap the response in a soap envelope when responding.

**Comment by devcritter** [comment]
Following discussion over skype with others of the OpenHIE team, it was decided the best course would be for the HIM to respond the same way as an XDS repo, so as to be standards compliant. This means the error would need to be returned as a repository response message with an XDS error code (in addition to the soap envelope).

**Comment by surangak** [comment]
Thats great! will there be a release with the latest series of fixes? or should we just checkout the code and build it ourselves? :-)

**Comment by devcritter** [comment]
We'll try get a release out soon - just need to test master a bit to make sure it's fit for release.

I see no problem if you do want to check it out; the code should be stable - plus it would help us test! ;)
